config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  
  resources :projects
  
  #get 'home/project'
  #root 'home#project'
  root 'projects#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    
      return unless user.present?
      can :read, :all
      return unless user.admin?
      can :manage, :all
    
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :projects
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ActionController::Base
    around_action :use_default_locale
    
    private
  
    def use_default_locale(&block)
      # Executes the request with the I18n.default_locale.
      # https://github.com/ruby-i18n/i18n/commit/9b14943d5e814723296cd501283d9343985fca4e
      I18n.with_locale(I18n.default_locale, &block)
    end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def project
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  
  before_action :set_project, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /projects or /projects.json
 
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    #@project = Project.new
    @project = current_user.projects.build
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    #@project = Project.new(project_params)
    @project = current_user.projects.build(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

def correct_user
  @project = current_user.projects.find_by(id: params[:id])
  redirect_to projects_path, notice: "Not Authorized to edit this project" if @project.nil?
end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :description, :user_id)
    end

    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :role, :admin)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/home/project.html.erb
<h1>Colaborate</h1>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MyBasecamp1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
  </head>
  <body>
<% if user_signed_in? %>
    <%= render 'home/header' %>
<% else %>
    <%= render 'home/index' %>
<% end %>
    <div class="container">
    <br/>
    <% if notice %>
      <%= render 'layouts/alerts' %>
  
    <% end %>

    <%= yield %>

  </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js" integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N" crossorigin="anonymous"></script>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  
  <br/>
  <div class="field form-group d-grid gap-2 col-9 mx-auto">
  <%= form.label :name %>
  <%= form.text_field :name, class:"form-control" %>
  </div>

  <div class="field form-group d-grid gap-2 col-9 mx-auto">
  <%= form.label :description %>
  <%= form.text_field :description, class:"form-control" %>
  </div>
  
  <div class="field form-group d-grid gap-2 col-9 mx-auto">
  <%= form.number_field :user_id, id: :project_user_id, class:"form-control",value: current_user.id, type: :hidden %>
  </div>
<br/>
  <div class="actions d-grid gap-2 d-md-block col-3 mx-auto">
    <%= form.submit class:'btn btn-secondary' %>
  </div>

<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Name:</strong>
    <%= project.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= project.description %>
  </p>

</div>

app/views/projects/_sidebar.html.erb
<nav class="navbar navbar-expand bg-body-tertiary fixed-top-start">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Offcanvas</h5>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            </a>
            <ul class="dropdown-menu">
              <li><%= button_to "Delete Project", @project, method: :delete, data: { confirm: "Are you sure?" }, class:"btn btn-secondary" %></li>
              <li><a class="dropdown-item" href="/projects"><img src="https://thumbs.dreamstime.com/b/eye-simple-icon-outline-vector-illustration-isolated-white-background-eps-file-available-125333237.jpg" alt="Logo" width="30" height="24" class="d-inline-block align-text-top">Project Overview</a></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/projects/edit.html.erb
  <figure class="text-center">
    <blockquote class="blockquote">
      <h1 class="fw-bold">Edit Project</h1>
    </blockquote>
  </figure> 
  
  <%= render 'projects/sidebar' %>

  <%= render "form", project: @project %>
  
  <% link_to "Back to projects", projects_path, class:"btn btn-secondary" %>

app/views/projects/index.html.erb
<% if user_signed_in? %>

  <figure class="text-center">
    <blockquote class="blockquote">
        <h1 class="fw-bold">Projects</h1>
    </blockquote>
  </figure>  
  

  <div id="projects">
    <% @projects.each do |project| %>
      <% if project.user == current_user %>
      <div class="card" style="width: 18rem;">
      <h4 class="card-header text-bg-success"><%= link_to project.name, project%> 
    </h4>
        <div class="card-body">
        <h6 class="card-title"> <%= project.description %></h6>
          <p class="card-text"></p>
          </div>
          <div class="card-footer btn-group text-bg-secondary" role="group" aria-label="Basic example">
          <%= button_to "Delete Project", project, method: :delete, data: { confirm: "Are you sure?" }, class:"btn btn-secondary btn-sm" %>
        </div>
        <% end %>
        </div>
      </div>
    <% end %> 
  </div>
<% else %>

<figure class="text-center">
    <blockquote class="blockquote">
                <h1 class="card-title"><strong>COLLABORATE</strong></h1>
                <p class="card-text">A project management tool for developers</p>
                <%= link_to "Sign Up", new_user_registration_path, class:"btn btn-primary" %>
                <%= link_to "Login", new_user_session_path, class:"btn btn-primary" %>    
    </blockquote>
</figure> 

<% end %>

app/views/projects/new.html.erb
<figure class="text-center">
  <blockquote class="blockquote">
      <h1 class="fw-bold">New Project</h1>
  </blockquote>
</figure>  

<%= render "form", project: @project %>

<br>

<div>
  <% link_to "Back to projects", projects_path, class:"btn btn-secondary" %>
</div>

app/views/projects/show.html.erb
<div class="card" style="width: 18rem;">
  <h4 class="card-header"> <%= @project.name %> 
  <a href="/projects/">
        <img src="https://thumbs.dreamstime.com/b/eye-simple-icon-outline-vector-illustration-isolated-white-background-eps-file-available-125333237.jpg" alt="Logo" width="30" height="24" class="d-inline-block align-text-top">
      </a>
  </h4>
  <div class="card-body text-bg-success">
  <h6 class="card-title"> <%= @project.description %></h6>
    <p class="card-text"></p>
    </div>
    <div class="card-footer btn-group text-bg-secondary" role="group">
    <%= link_to "Edit", edit_project_path(@project), class:"btn btn-secondary btn-sm" %>
    <%= button_to "Delete project", @project, method: :delete, data: { confirm: "Are you sure?" }, class:"btn btn-secondary btn-sm" %>
  </div>
</div>